<a href="https://colab.research.google.com/github/DerinOgrenme2021/DersMateryali/blob/main/SemihYumusak.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World")

Hello World


In [10]:
a = 5

In [11]:
print(a)
print(type(a))

5
<class 'int'>


In [12]:
a="semih"

In [13]:
print(a)
print(type(a))


semih
<class 'str'>


In [14]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [16]:
i = 0
while i<10:
  i += 1
  print (i)

1
2
3
4
5
6
7
8
9
10


In [17]:
a = [1,2,3,4]

for b in a:
  print (b)

1
2
3
4


In [18]:
def my_funct():
  print("this is my funct")

In [19]:
my_funct()

this is my funct


In [20]:
class myClass:
  a = 1
  def my_funct(self, b):
    print(b)

In [21]:
c = myClass()
c.my_funct("hello class")

hello class


In [23]:
import numpy
a = numpy.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
